apiVersion: v1
kind: Namespace
metadata:
  name: converged-frontier
  labels:
    blueteamvillage.org/disable-quotas: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
